swagger: '2.0'
info:
  title: Bivi API
  description: API para el servicio de fabricación de Bivi
  version: 0.0.1
host: bivi-api-gateway.uc.gateway.dev
schemes:
  - https
produces:
  - application/json
securityDefinitions:
  api_key:
    type: apiKey
    name: x-api-key
    in: header
paths:
  /v1/{name}:
    get:
      summary: Decir hola desde bivi-1
      operationId: hi
      parameters:
      - in: header
        name: x-api-key
        required: true
        type: string
      - in: path
        name: name
        required: true
        type: string
        minimum: 1
        description: Parameter description in Markdown.
      responses:
          '200':
            description: OK
            schema:
              type: string
              example: Hola desde bivi-1
      x-google-backend:
        address: https://java-hello-1063658746297.us-central1.run.app
        path_translation: APPEND_PATH_TO_ADDRESS 